# Generated by Django 4.2.2 on 2023-06-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_followings_alter_user_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='user'),
            preserve_default=False,
        ),
    ]
