# Generated by Django 4.2.2 on 2023-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_post_sad'),
        ('account', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sad',
            field=models.ManyToManyField(blank=True, null=True, to='content.post'),
        ),
    ]
