# Generated by Django 4.2.2 on 2023-06-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_post_sad'),
        ('account', '0004_user_is_sad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_sad',
            field=models.ManyToManyField(blank=True, null=True, related_name='sad_users', to='content.post'),
        ),
    ]
