# Generated by Django 4.2.2 on 2023-06-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/user/default.png', upload_to='user'),
        ),
    ]
