# Generated by Django 4.2.2 on 2023-06-18 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_alter_post_author_alter_post_saved_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='saved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
