# Generated by Django 4.2.2 on 2023-06-18 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_alter_post_saved_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='saved_user',
        ),
        migrations.AddField(
            model_name='post',
            name='saved_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
